Rollback apricot-hugo-theme to avoid build error
The theme author incorrectly added example config.toml entries
to theme.toml, leading to the following build error:

    Error: Error building site: failed to parse page metadata for
    "apricot-hugo-theme/index.md": Near line 18 (last key parsed 'title'):
    Key 'title' has already been defined.

See https://github.com/otterpro/apricot-hugo-theme/issues/1